apiVersion: v1
kind: Service
metadata:
  labels:
    app: chirpstack-rest-api
  name: chirpstack-rest-api
spec:
  ports:
  - name: web
    port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    app: chirpstack-rest-api
  type: ClusterIP
