apiVersion: v1
kind: Service
metadata:
  labels:
    app: mosquitto
  name: mosquitto
spec:
  ports:
  - name: web
    port: 1883
    protocol: TCP
    targetPort: 1883
  selector:
    app: mosquitto
  type: ClusterIP
