apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: chirpstack-gateway-bridge-eu868

resources:
- deployment.yaml
- service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - configuration/chirpstack-gateway-bridge.toml
  name: chirpstack-gateway-bridge-eu868-configuration
